import { getDb } from '../../db.js';
import {
  getRegisteredAgent,
  TOOL_FAMILY_MAP,
  type RegisteredAgentRecord,
} from '../db/agent-accessors.js';
import {
  streamLlmResponse,
  type LlmProviderConfig,
  type LlmSecret,
  type LlmToolDefinition,
  type LlmMessage,
  type LlmStreamEvent,
  LlmClientError,
} from './llm-client.js';

// ---------------------------------------------------------------------------
// Types: Execution Context and Events
// ---------------------------------------------------------------------------

/**
 * ExecutionContext encapsulates all Talk-related context provided to the agent.
 * For Main channel execution (context=null), this is omitted entirely.
 */
export interface ExecutionContext {
  /** System prompt prefix for this Talk (goal, rules, summary, sources) */
  systemPrompt: string;

  /** Tool definitions for reading Talk context (always included for Talk execution) */
  contextTools: LlmToolDefinition[];

  /** Tool definitions for data connectors bound to this Talk */
  connectorTools: LlmToolDefinition[];

  /** Conversation history for this Talk */
  history: LlmMessage[];
}

/**
 * ExecutionEvent is emitted during agent execution to stream progress to the caller.
 */
export type ExecutionEvent =
  | {
      type: 'started';
      runId: string;
      agentId: string;
      providerId: string;
      modelId: string;
    }
  | {
      type: 'text_delta';
      text: string;
    }
  | {
      type: 'tool_call';
      toolName: string;
      arguments: Record<string, unknown>;
    }
  | {
      type: 'tool_result';
      toolName: string;
      result: string;
      isError?: boolean;
    }
  | {
      type: 'awaiting_confirmation';
      confirmationId: string;
      toolName: string;
      actionSummary: string;
    }
  | {
      type: 'usage';
      inputTokens: number;
      outputTokens: number;
      estimatedCostUsd?: number;
    }
  | {
      type: 'completed';
      content: string;
    }
  | {
      type: 'failed';
      errorCode: string;
      errorMessage: string;
    }
  | {
      type: 'cancelled';
    };

/**
 * Final result of an agent execution.
 */
export interface AgentExecutionResult {
  /** The final content generated by the agent */
  content: string;

  /** Execution metadata */
  agentId: string;
  providerId: string;
  modelId: string;

  /** Token usage and estimated cost */
  usage?: {
    inputTokens: number;
    outputTokens: number;
    estimatedCostUsd?: number;
  };
}

// ---------------------------------------------------------------------------
// Main Execution Function
// ---------------------------------------------------------------------------

/**
 * Execute an agent with optional Talk context and streaming output.
 *
 * Flow:
 * 1. Load agent config (provider, model, tool permissions)
 * 2. Resolve provider credentials
 * 3. Filter tools by agent permissions (+ always include context tools if in Talk)
 * 4. Build LLM messages (system prompt + history + user message)
 * 5. Call LLM, stream events
 * 6. Handle tool loop: execute tools, append results, call LLM again (max 10 iterations)
 * 7. Handle fallback: if primary provider fails, try fallback steps
 * 8. Return result
 *
 * @param agentId - ID of the registered agent to execute
 * @param context - Talk execution context, or null for Main channel
 * @param userMessage - User's message to process
 * @param options - Execution options
 * @returns Final execution result
 */
export async function executeWithAgent(
  agentId: string,
  context: ExecutionContext | null,
  userMessage: string,
  options: {
    runId: string;
    userId: string;
    signal?: AbortSignal;
    emit?: (event: ExecutionEvent) => void;
    executeToolCall?: (
      toolName: string,
      args: Record<string, unknown>,
    ) => Promise<{ result: string; isError?: boolean }>;
  },
): Promise<AgentExecutionResult> {
  const db = getDb();
  const emit = options.emit || (() => {});

  // -----------
  // Step 1: Load agent config
  // -----------
  const agent = getRegisteredAgent(agentId);
  if (!agent) {
    const errorCode = 'AGENT_NOT_FOUND';
    const errorMessage = `Agent ${agentId} not found`;
    emit({ type: 'failed', errorCode, errorMessage });
    throw new Error(errorMessage);
  }

  if (agent.enabled !== 1) {
    const errorCode = 'AGENT_DISABLED';
    const errorMessage = `Agent ${agentId} is disabled`;
    emit({ type: 'failed', errorCode, errorMessage });
    throw new Error(errorMessage);
  }

  // -----------
  // Step 2: Resolve provider config and secrets
  // -----------
  let providerRecord: any = db
    .prepare('SELECT * FROM llm_providers WHERE id = ?')
    .get(agent.provider_id);

  if (!providerRecord) {
    const errorCode = 'PROVIDER_NOT_FOUND';
    const errorMessage = `Provider ${agent.provider_id} not found`;
    emit({ type: 'failed', errorCode, errorMessage });
    throw new Error(errorMessage);
  }

  // Resolve provider config
  const providerConfig: LlmProviderConfig = {
    baseUrl: providerRecord.base_url || undefined,
    apiFormat: providerRecord.type,
    authScheme: providerRecord.auth_scheme || 'x_api_key',
  };

  // Fetch and decrypt provider secret
  let secret: LlmSecret | undefined;
  const secretRecord: any = db
    .prepare('SELECT ciphertext FROM llm_provider_secrets WHERE provider_id = ?')
    .get(agent.provider_id);

  if (secretRecord) {
    try {
      // For now, assume ciphertext is just JSON (no actual encryption)
      secret = JSON.parse(secretRecord.ciphertext);
    } catch {
      const errorCode = 'SECRET_DECRYPTION_FAILED';
      const errorMessage = `Failed to decrypt provider secret for ${agent.provider_id}`;
      emit({ type: 'failed', errorCode, errorMessage });
      throw new Error(errorMessage);
    }
  }

  // -----------
  // Step 3: Filter tools by agent permissions
  // -----------
  let agentPermissions: Record<string, boolean> = {};
  try {
    agentPermissions = JSON.parse(agent.tool_permissions_json);
  } catch {
    const errorCode = 'INVALID_TOOL_PERMISSIONS';
    const errorMessage = `Failed to parse tool_permissions_json for agent ${agentId}`;
    emit({ type: 'failed', errorCode, errorMessage });
    throw new Error(errorMessage);
  }

  // Resolve enabled tools from TOOL_FAMILY_MAP
  const enabledToolNames = new Set<string>();
  for (const [family, enabled] of Object.entries(agentPermissions)) {
    if (enabled === true) {
      const familyTools = TOOL_FAMILY_MAP[family] || [];
      for (const tool of familyTools) {
        enabledToolNames.add(tool);
      }
    }
  }

  // Build tool array from agent's own tools (will be provided by caller via executeToolCall)
  // Plus context tools and connector tools if in Talk context
  const tools: LlmToolDefinition[] = [];

  if (context) {
    // Talk execution: always include context tools and connector tools
    tools.push(...context.contextTools);
    tools.push(...context.connectorTools);
  }

  // TODO: Add agent's own tools here once they're available in the execution context
  // For now, assume they're passed via executeToolCall handler

  // -----------
  // Step 4: Build LLM messages
  // -----------
  const messages: LlmMessage[] = [];

  // Add Talk history if in Talk context
  if (context && context.history.length > 0) {
    messages.push(...context.history);
  }

  // Add user message
  messages.push({
    role: 'user',
    content: userMessage,
  });

  // Build system prompt
  let systemPrompt = '';
  if (context) {
    // Prepend Talk context to system prompt
    systemPrompt = context.systemPrompt;
    if (agent.system_prompt) {
      systemPrompt += '\n\n' + agent.system_prompt;
    }
  } else {
    // Main channel: just agent's system prompt
    systemPrompt = agent.system_prompt || '';
  }

  // -----------
  // Step 5: Stream LLM response
  // -----------
  emit({
    type: 'started',
    runId: options.runId,
    agentId,
    providerId: agent.provider_id,
    modelId: agent.model_id,
  });

  let finalContent = '';
  let accumulatedTokens = { inputTokens: 0, outputTokens: 0, estimatedCostUsd: 0 };

  try {
    const stream = streamLlmResponse(
      providerConfig,
      secret!,
      agent.model_id,
      messages,
      {
        tools,
        signal: options.signal,
      },
    );

    for await (const event of stream) {
      if (options.signal?.aborted) {
        emit({ type: 'cancelled' });
        return {
          content: finalContent,
          agentId,
          providerId: agent.provider_id,
          modelId: agent.model_id,
        };
      }

      if (event.type === 'text_delta') {
        finalContent += event.text;
        emit({ type: 'text_delta', text: event.text || '' });
      } else if (event.type === 'tool_call_start') {
        const toolName = event.toolCall?.name || '';
        const toolArguments = event.toolCall?.arguments ? JSON.parse(event.toolCall.arguments) : {};
        emit({
          type: 'tool_call',
          toolName,
          arguments: toolArguments,
        });

        // Execute the tool
        if (options.executeToolCall) {
          try {
            const { result, isError } = await options.executeToolCall(
              toolName,
              toolArguments,
            );
            emit({
              type: 'tool_result',
              toolName,
              result,
              isError,
            });

            // Append tool result to messages for next iteration
            messages.push({
              role: 'assistant',
              content: finalContent,
            });
            messages.push({
              role: 'user',
              content: `Tool result for ${toolName}: ${result}`,
            });

            // TODO: Re-call LLM with appended result (implement tool loop)
          } catch (err) {
            const errorMsg = String(err);
            emit({
              type: 'tool_result',
              toolName,
              result: errorMsg,
              isError: true,
            });
          }
        }
      } else if (event.type === 'usage') {
        accumulatedTokens = {
          inputTokens: event.usage?.inputTokens || 0,
          outputTokens: event.usage?.outputTokens || 0,
          estimatedCostUsd: 0,
        };
        emit({
          type: 'usage',
          inputTokens: event.usage?.inputTokens || 0,
          outputTokens: event.usage?.outputTokens || 0,
          estimatedCostUsd: 0,
        });
      }
    }
  } catch (err) {
    if (err instanceof LlmClientError) {
      // TODO: Implement fallback logic here
      // For now, just fail
      emit({
        type: 'failed',
        errorCode: err.failureClass || 'LLM_ERROR',
        errorMessage: err.message,
      });
      throw err;
    }
    throw err;
  }

  // -----------
  // Step 6: Emit completion
  // -----------
  emit({
    type: 'completed',
    content: finalContent,
  });

  return {
    content: finalContent,
    agentId,
    providerId: agent.provider_id,
    modelId: agent.model_id,
    usage: accumulatedTokens,
  };
}
